create table if not exists public.gallery (

  id bigint generated by default as identity
  primary key,

  caption text,

  image_url text not null,

  storage_path text not null,

  created_at timestamptz
  default now()

);


alter table public.gallery
enable row level security;


create policy
"Public can view gallery"

on public.gallery

for select

to anon, authenticated

using (true);


create policy
"Authenticated can insert gallery"

on public.gallery

for insert

to authenticated

with check (true);


create policy
"Public can view gallery files"

on storage.objects

for select

to public

using (
  bucket_id = 'gallery'
);


create policy
"Authenticated can upload gallery files"

on storage.objects

for insert

to authenticated

with check (
  bucket_id = 'gallery'
);
